dist: trusty
sudo: required

language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - yarn install

# We are running browser tests
before_script:
  - export TZ=Europe/Helsinki
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn lint
  - yarn test:ci

after_success:
  - codecov < coverage/lcov.info

notifications:
  slack:
    secure: jJCkbwetAYxE3BqMtDfLo14AqLoLGlF7xpIja+MjH6D4tGAWM0FyBfjxwXZBun2ILp41emiZbUPcunTup4Y+IRNi/k09zV56hXDZ+TvxJUwcq2chc0fu83bg3Sbvz+qTw9dxvfTIDMk0T4S1BpJuXT6Bva7ZBtI0rI5ZxMLoKiwTJGnZdy6DK6wByi/uRXqBYzQx3ePUg4kfnn/gq15A64EgjYsfBa1c7eSgf/qK96UkkKZrKDDcm/Ae6Gqz1tJVs4QlQLEz3PPqlkpCW/ECXjiD/UJHCRwXmnXVxAsMqIzdDNn+nkwpX1xthlawBWzpCVJKZ1RMjQZ0Plimno1QrBZLOtOiG4SJjPTD1P9Sq4C6lU4DvE1LKhAOjQmeu3PcDpc1eaIqJWqAsAjXTKHXGo7MdC62lcOMdi0x9Kp/TiiPBaLOOYm+r5uKuKj/+c5I86UrNMdy7ZMvUVRKn6OXs5NlZWSlpX1Xvo3C27nFxMGr65l6B9Xk7S6HHXOtMBCSmHl/pZSWnVHn9rCCGf6OSO0GH2XGbD+XtVDm5m7EgGaxt4xPPKKbX5YZ8zoGdPVRd2WxBKpnhr8HLecZCRXq4uU/1VIrC97hfIVISr5lUDA4e7sKhFrp/TD6J0NHa3lZoXar6M4uwkgRrhyZOc0WrrJAWTxQ4TAJqPxwrNPl0Jo=
