version: '3'

services:
  node-app:
    container_name: varaamo-prod
    build:
      args:
        NODE_ENV: production
    ports:
      - '8080:8080'
      - '5858:5858'
      - '9229:9229'
    environment:
      - NODE_ENV=production
