name: Cypress Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [18]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y

      - name: create env file
        run: |
          touch .env
          echo PORT=3000 >> .env
          cat .env

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install-command: npm ci --silent
          build: npm run build
          start: npm run start:production
